# Generated by Django 6.0.8 on 2026-08-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0002_remove_document_owner_document_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='guest_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
