import os

from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_mistralai import ChatMistralAI

# ----------------------------------------------------------------------
# Load environment variables from .env.
# ----------------------------------------------------------------------
load_dotenv()

# ----------------------------------------------------------------------
# Create the LLM client.
# Keep temperature low for factual RAG answers.
# ----------------------------------------------------------------------

llm = ChatMistralAI(
    model="mistral-small-latest",
    api_key=os.getenv("MISTRAL_API_KEY"),
    temperature=0.7,
)


PROMPT = ChatPromptTemplate.from_template(
    '''
You are a careful question-answering assistant.

Use the conversation history only to maintain conversational continuity.

Use ONLY the provided context for factual information.

Rules:
- Do not use outside knowledge.
- If the answer is not explicitly supported by the context,
  reply exactly:
  "I couldnt find any relevant information from the documents"
- Keep the answer concise and factual.
- If the context contains a list, include all items from that list.
- You may refer to previously discussed topics naturally (for example,
  "this architecture" or "the transformer discussed earlier")
  only if they appear in the conversation history.

Conversation history:
{history}

Context:
{context}

Question:
{question}

Answer:
'''
)


def generate_answer(
    question: str,
    retrieved_docs: list[str],
    history: str = '',
) -> str:
    """
    Generate an answer grounded in retrieved document chunks while
    preserving conversational continuity.

    Parameters
    ----------
    question:
        Standalone question used for retrieval.
    retrieved_docs:
        Retrieved chunk texts.
    history:
        Recent conversation history.

    Returns
    -------
    str
        Grounded answer generated by the LLM.
    """

    # ------------------------------------------------------------------
    # Join retrieved chunks into a single context block.
    # ------------------------------------------------------------------
    context = '\n\n'.join(retrieved_docs)

    chain = PROMPT | llm

    response = chain.invoke(
        {
            'context': context,
            'question': question,
            'history': history,
        }
    )

    content = response.content

    # Gemini may return a list of content parts
    if isinstance(content, list):
        texts = []
        for part in content:
            if isinstance(part, dict):
                if part.get("type") == "text":
                    texts.append(part.get("text", ""))
            elif hasattr(part, "text"):
                texts.append(part.text)
            else:
                texts.append(str(part))

        return "\n".join(texts).strip()

    return str(content).strip()


if __name__ == '__main__':
    sample_context = [
        (
            'Retrieval-Augmented Generation (RAG) combines retrieval '
            'of relevant documents with text generation.'
        ),
        (
            'RAG retrieves relevant chunks before generating an answer.'
        ),
    ]

    sample_history = (
        'User: Explain RAG.\n'
        'Assistant: RAG combines retrieval and generation.'
    )

    question = 'Explain it in more detail.'

    answer = generate_answer(
        question=question,
        retrieved_docs=sample_context,
        history=sample_history,
    )

    print('Question:', question)
    print('Answer:', answer)