from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama


# ----------------------------------------------------------------------
# Create the local LLM client through Ollama.
#
# Ollama runs locally on your machine, so no API key is required.
# Make sure the model has been downloaded with:
#
#     ollama pull mistral
#
# ----------------------------------------------------------------------

llm = ChatOllama(
    model="llama3.2:3b",
    temperature=0.7,
)


# ----------------------------------------------------------------------
# Prompt used for grounded RAG answers.
# ----------------------------------------------------------------------

PROMPT = ChatPromptTemplate.from_template(
    '''
You are a careful question-answering assistant.

Use the conversation history only to maintain conversational continuity.

Use ONLY the provided context for factual information.

Rules:
- Do not use outside knowledge.
- If the answer is not explicitly supported by the context,
  reply exactly:
  "I couldnt find any relevant information from the documents"
- Keep the answer concise and factual.
- If the context contains a list, include all items from that list.
- You may refer to previously discussed topics naturally (for example,
  "this architecture" or "the transformer discussed earlier")
  only if they appear in the conversation history.
  
Formatting rules:
- Use Markdown formatting.
- Use ## headings for major sections when the answer has multiple sections.
- Make important terms bold using **bold**.
- Use bullet points when presenting multiple items.
- Use numbered lists when explaining sequential steps or procedures.
- Use short paragraphs rather than large blocks of text.
- Use code blocks when presenting code.
- Use tables only when they make a comparison significantly clearer.
- Do not create unnecessary headings for very short answers.
- Do not use excessive formatting.

Conversation history:
{history}

Context:
{context}

Question:
{question}

Answer:
'''
)


def generate_answer(
    question: str,
    retrieved_docs: list[str],
    history: str = '',
) -> str:
    """
    Generate an answer grounded in retrieved document chunks while
    preserving conversational continuity.

    Parameters
    ----------
    question:
        Standalone question used for retrieval.

    retrieved_docs:
        Retrieved chunk texts.

    history:
        Recent conversation history.

    Returns
    -------
    str
        Grounded answer generated by the local Ollama LLM.
    """

    # ------------------------------------------------------------------
    # Join retrieved chunks into a single context block.
    # ------------------------------------------------------------------

    context = '\n\n'.join(retrieved_docs)

    # ------------------------------------------------------------------
    # Create the prompt → LLM chain.
    # ------------------------------------------------------------------

    chain = PROMPT | llm

    # ------------------------------------------------------------------
    # Invoke the local Ollama model.
    # ------------------------------------------------------------------

    response = chain.invoke(
        {
            'context': context,
            'question': question,
            'history': history,
        }
    )

    # ------------------------------------------------------------------
    # Extract the generated content.
    # ------------------------------------------------------------------

    content = response.content

    # Handle structured content if returned by the model.
    if isinstance(content, list):
        texts = []

        for part in content:
            if isinstance(part, dict):
                if part.get("type") == "text":
                    texts.append(part.get("text", ""))

            elif hasattr(part, "text"):
                texts.append(part.text)

            else:
                texts.append(str(part))

        return "\n".join(texts).strip()

    return str(content).strip()


# ----------------------------------------------------------------------
# Standalone test
# ----------------------------------------------------------------------

if __name__ == '__main__':

    sample_context = [
        (
            'Retrieval-Augmented Generation (RAG) combines retrieval '
            'of relevant documents with text generation.'
        ),
        (
            'RAG retrieves relevant chunks before generating an answer.'
        ),
    ]

    sample_history = (
        'User: Explain RAG.\n'
        'Assistant: RAG combines retrieval and generation.'
    )

    question = 'Explain it in more detail.'

    answer = generate_answer(
        question=question,
        retrieved_docs=sample_context,
        history=sample_history,
    )

    print('Question:', question)
    print('Answer:', answer)